# Config file for [Air](https://github.com/cosmtrek/air) in TOML format
root = "."
tmp_dir = "tmp"

[build]
cmd = "make build-debug"
bin = "./bin/queue-shuffle-debug"
full_bin = "export $(grep -v '^#' .env | xargs) && dlv exec ./bin/queue-shuffle-debug --listen=127.0.0.1:2345 --headless=true --api-version=2 --accept-multiclient --continue --log -- "
include_ext = ["go"]
exclude_dir = [".vscode", ".github", "bin", "tmp"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
args_bin = ["server"]

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true